[package]
name = "r14_patterns"
version = "0.1.0"
authors = ["John Tucker <john@larkintuckerllc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
